name: 🚀 Feature Request
description: New features and improvements
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the new feature.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: |
        A simple example of the new feature in action.
