name: "PHP_CodeSniffer"

on:
    push:
        branches:
            - 'master'
    pull_request:
        branches:
            - 'master'

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Run PHPCS inspection
                uses: rtCamp/action-phpcs-code-review@v2
                env:
                    GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
                with:
                    args: "PSR12,PHPCompatibility"