name: "PHP_CodeSniffer"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - '**.php'
      - 'phpcs.xml'
      - '.github/workflows/phpcs.yml'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run PHPCS
        run: make phpcs-dry-run
